
#
JAVA_HOME=/usr/local/openjdk-8
HDFS_NAMENODE_USER=hadoop
HDFS_DATANODE_USER=hadoop
HDFS_SECONDARYNAMENODE_USER=hadoop
export HADOOP_ROOT_LOGGER=DEBUG,console
export HADOOP_DAEMON_ROOT_LOGGER=DEBUG,RFA
export HADOOP_SECURITY_LOGGER=DEBUG,NullAppender
export HDFS_AUDIT_LOGGER=DEBUG,NullAppender
